[buildPlans.iosevka-comfy]       # <iosevka-comfy> is your plan name
family = "Iosevka Comfy"         # Font menu family name
spacing = "fixed"                # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
serifs = "sans"                  # Optional; Values: `sans` or `slab`

###################################################################################################
# Configure variants

# # Optional; Whether to inherit a `ss##` variant
# [buildPlans.iosevka-comfy.variants]
# inherits = "ss01"

# Optional; Configure single character's variant
[buildPlans.iosevka-comfy.variants.design]
cv01 = 1    # A cap straight
cv02 = 1    # B cap straight
cv03 = 1    # C cap serifless
cv04 = 2    # D cap curly
cv05 = 1    # E cap serifless
cv06 = 1    # F cap serifless
cv07 = 4    # G cap toothed
cv08 = 1    # H cap serifless
cv09 = 3    # I cap short serifs
cv10 = 2    # J cap serified
cv11 = 2    # K cap curly
cv12 = 1    # L cap serifless
cv13 = 1    # M cap short middle leg
cv14 = 1    # N cap symmetric
cv15 = 1    # P cap straight
cv16 = 4    # Q cap crossing tail
cv17 = 1    # R cap straight
cv18 = 1    # S cap serifless
cv19 = 1    # T cap serifless
cv20 = 3    # U cap serifless
cv21 = 1    # V cap straight
cv22 = 2    # W cap curly short middle top
cv23 = 1    # X cap straight
cv24 = 1    # Y cap straight
cv25 = 1    # Z cap straight
cv27 = 1    # b toothed
cv28 = 1    # c serifless
cv29 = 1    # d toothed
cv33 = 1    # h straight
cv34 = 10   # i serified flat tailed
cv35 = 6    # j flat hook serified
cv37 = 10   # l serified flat tailed
cv42 = 9    # r compact
cv43 = 1    # s serifless
cv44 = 3    # t flat hook
cv49 = 6    # y cursive flat terminal hook
cv53 = 1    # Λ lambda cap straight
cv54 = 2    # α alpha straight tailed
cv55 = 1    # γ gamma cap straight
cv56 = 1    # ε epsilon serifless
cv58 = 6    # ι iota serified flat tailed
cv59 = 2    # λ lambda top tailed
cv65 = 2    # 3 arched
cv67 = 2    # 5 open contour
cv69 = 1    # 7 straight
cv70 = 3    # 8 two asymmetric circles
cv72 = 2    # ~ tilde low
cv73 = 2    # * asterisk five-pointed low
cv74 = 1    # _ underscore right below baseline
cv76 = 1    # ^ uptick high
cv77 = 1    # ( parentheses normal slope
cv78 = 1    # { braces straight (simplified)
cv79 = 1    # # column straight
cv82 = 1    # $ dollar open
cv83 = 1    # ¢ cent open
cv84 = 1    # % percent dots
cv85 = 1    # | bar natural slope
cv86 = 2    # ≥ equal-or-{higher,lower} slanted
cv87 = 1    # ' single quote straight
cv88 = 1    # ` grave/backtick straight
cv89 = 1    # ? smooth

# Optional; Configure single character's variant for Upright and Oblique; Overrides [design]
[buildPlans.iosevka-comfy.variants.upright]
cv26 = 1    # a double storey
cv30 = 1    # e straight
cv31 = 16   # f serifless bottom flat top crossbar at x height
cv32 = 8    # g single storey flat hook earless
cv36 = 1    # k straight
cv38 = 9    # m earless double arch
cv39 = 3    # n earless straight
cv40 = 2    # p earless
cv41 = 3    # q earless
cv45 = 1    # u straight
cv46 = 1    # v straight
cv47 = 1    # w straight short middle top
cv48 = 1    # x straight
cv50 = 1    # z straight
cv62 = 9    # 0 oval dotted
cv63 = 2    # 1 serified with base
cv64 = 1    # 2 straight
cv66 = 3    # 4 semi-open contour
cv68 = 3    # 6 straight
cv71 = 3    # 9 straight
cv80 = 2    # & et open top (ampersand)
cv81 = 1    # @ at threefold

# Optional; Configure single character's variant for Italic only; Overrides [design]
[buildPlans.iosevka-comfy.variants.italic]
cv26 = 10   # a single storey earless tailed
cv30 = 2    # e curly
cv31 = 14   # f extended flat top bottom hook
cv32 = 7    # g single storey flat hook
cv36 = 2    # k curly
cv38 = 2    # m straight middle shortleg
cv39 = 1    # n straight
cv40 = 1    # p straight
cv41 = 1    # q straight
cv45 = 4    # u tailed
cv46 = 2    # v curly
cv47 = 2    # w curly short middle top
cv48 = 2    # x curly
cv50 = 4    # z curly
cv62 = 4    # 0 dotted
cv63 = 1    # 1 serified no base
cv64 = 2    # 2 curly
cv66 = 1    # 4 closed contour crossing
cv68 = 1    # 6 closed contour
cv71 = 1    # 9 closed contour
cv80 = 4    # & et open top toothed (ampersand)
cv81 = 3    # @ at short

# End variant section
###################################################################################################

###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.
[buildPlans.iosevka-comfy.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy.weights.bold]
shape = 700
menu  = 700
css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slopes would be built.

[buildPlans.iosevka-comfy.slopes]
upright = "normal"
italic = "italic"

# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

[buildPlans.iosevka-comfy.widths.normal]
shape = 550        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

# [buildPlans.iosevka-comfy.widths.normal]
# shape = 500        # Unit Width, measured in 1/1000 em.
# menu  = 5          # Width grade for the font's names.
# css   = "normal"   # "font-stretch' property of webfont CSS.

# [buildPlans.iosevka-comfy.widths.extended]
# shape = 600
# menu  = 7
# css   = "expanded"

# End width section
###################################################################################################

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

[buildPlans.iosevka-comfy.metric-override]
leading = 1100

[buildPlans.iosevka-comfy.metric-override.multiplies]
sb = 1.0625

[buildPlans.iosevka-comfy.metric-override.adds]
sb = 15

# End metric override section
###################################################################################################
