# Iosevka Comfy main style
# ------------------------
[buildPlans.iosevka-comfy]  # <iosevka-comfy> is your plan name
family = "Iosevka Comfy"    # Font menu family name
spacing = "normal"          # Optional; Values: `normal`, `quasi-proportional`, `quasi-proportional-extension-only`, `term`, `fontconfig-mono`, or `fixed`
serifs = "sans"             # Optional; Values: `sans` or `slab`
export-glyph-names = false  # Set this to true for ligature support in Kitty (increased file size)

[buildPlans.iosevka-comfy.variants.design]
cv01 = 1    # A cap straight
cv02 = 1    # B cap straight
cv03 = 1    # C cap serifless
cv04 = 6    # D cap curly with top and bottom serif (without serifs TODO reads like TOOO at small point sizes)
cv05 = 1    # E cap serifless
cv06 = 1    # F cap serifless
cv07 = 4    # G cap toothed
cv08 = 1    # H cap serifless
cv09 = 1    # I cap long serifs
cv10 = 2    # J cap serified
cv11 = 2    # K cap curly
cv12 = 1    # L cap serifless
cv13 = 3    # M cap short middle leg slanted sides
cv14 = 1    # N cap symmetric
cv15 = 1    # P cap straight
cv16 = 4    # Q cap crossing tail
cv17 = 1    # R cap straight
cv18 = 1    # S cap serifless
cv19 = 1    # T cap serifless
cv20 = 3    # U cap rounded serifless
cv21 = 1    # V cap straight
cv22 = 1    # W straight
cv23 = 1    # X cap straight
cv24 = 1    # Y cap straight
cv25 = 1    # Z cap straight
cv28 = 1    # c serifless
cv33 = 1    # h straight
cv34 = 10   # i serified flat tailed
cv35 = 6    # j flat hook serified
cv37 = 10   # l serified flat tailed
cv42 = 9    # r compact
cv43 = 1    # s serifless
cv44 = 2    # t flat hook
cv49 = 6    # y cursive flat terminal hook
cv53 = 1    # Λ, Δ lambda and delta cap straight
cv54 = 2    # α alpha straight tailed
VXAA = 1    # δ delta rounded top
cv55 = 1    # Γ gamma cap straight
cv56 = 6    # ι iota serified flat tailed
cv57 = 2    # λ lambda top tailed
VXAC = 1    # μ me tailless
VXAB = 2    # ξ xe flat top
cv71 = 13   # 0 oval dashed forward slash
cv74 = 2    # 3 arched
cv76 = 2    # 5 open contour
cv78 = 1    # 7 straight
cv79 = 3    # 8 two asymmetric circles
cv81 = 2    # ~ tilde low
cv82 = 2    # * asterisk five-pointed low
cv83 = 1    # _ underscore right below baseline
cv85 = 1    # ^ uptick high
cv86 = 1    # ( parentheses normal slope
cv87 = 2    # { braces curly
cv88 = 1    # # column straight
cv90 = 4    # @ three-fold, tall height
cv91 = 2    # $ dollar strike through
cv92 = 2    # ¢ cent strike through
cv93 = 1    # % percent dots
cv94 = 1    # | bar natural slope
cv95 = 1    # ' single quote straight
cv96 = 1    # ` grave/backtick straight
cv97 = 1    # ? smooth
cv98 = 2    # .:; square punctuation marks
cv99 = 2    # ijäöü square diacretics
VXLA = 2    # ≥ equal-or-{higher,lower} slanted

[buildPlans.iosevka-comfy.variants.upright]
cv26 = 3    # a double storey rounded
cv27 = 2    # b rounded
cv29 = 2    # d rounded
cv30 = 1    # e straight
cv31 = 16   # f serifless bottom flat top crossbar at x height
cv32 = 9    # g single storey flat hook earless cornered top
cv36 = 1    # k straight
cv38 = 6    # m earless double arch short middle leg
cv39 = 3    # n earless straight
cv40 = 2    # p earless
cv41 = 2    # q earless
cv45 = 2    # u rounded
cv46 = 1    # v straight
cv47 = 1    # w straight
cv48 = 1    # x straight
cv50 = 1    # z straight
cv72 = 3    # 1 serified with base
cv73 = 1    # 2 straight
cv75 = 3    # 4 semi-open contour
cv77 = 3    # 6 straight
cv80 = 3    # 9 straight
cv89 = 2    # & et open top (ampersand)

[buildPlans.iosevka-comfy.variants.italic]
cv26 = 1    # a double storey straight
cv27 = 1    # b straight
cv29 = 1    # d straight
cv30 = 2    # e curly
cv31 = 14   # f extended flat top bottom hook
cv32 = 7    # g single storey flat hook
cv36 = 2    # k curly
cv38 = 2    # m straight middle shortleg
cv39 = 1    # n straight
cv40 = 1    # p straight
cv41 = 1    # q straight
cv45 = 1    # u straight
cv46 = 2    # v curly
cv47 = 2    # w curly short middle top
cv48 = 2    # x curly
cv50 = 4    # z curly
cv72 = 2    # 1 serified no base
cv73 = 2    # 2 curly
cv75 = 1    # 4 closed contour crossing
cv77 = 1    # 6 closed contour
cv80 = 1    # 9 closed contour
cv89 = 4    # & et open top toothed (ampersand)

[buildPlans.iosevka-comfy.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-comfy.weights.semilight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-comfy.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-comfy.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-comfy.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-comfy.widths.normal]
shape = 525
menu  = 5
css   = "normal"


# Fixed spacing (no ligatures)
# ----------------------------
[buildPlans.iosevka-comfy-fixed]
family = "Iosevka Comfy Fixed"
spacing = "fixed"
serifs = "sans"
export-glyph-names = false

# It seems we can inherit variants, but not weights, slopes, widths,
# metric-override...
[buildPlans.iosevka-comfy-fixed.variants]
inherits = "buildPlans.iosevka-comfy"

[buildPlans.iosevka-comfy-fixed.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-comfy-fixed.weights.semilight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy-fixed.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy-fixed.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-comfy-fixed.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-comfy-fixed.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-comfy-fixed.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-comfy-fixed.widths.normal]
shape = 525
menu  = 5
css   = "normal"


# Duo spacing (quasi-proportional)
# --------------------------------
[buildPlans.iosevka-comfy-duo]
family = "Iosevka Comfy Duo"
spacing = "quasi-proportional"
serifs = "sans"
export-glyph-names = false

# It seems we can inherit variants, but not weights, slopes, widths,
# metric-override...
[buildPlans.iosevka-comfy-duo.variants]
inherits = "buildPlans.iosevka-comfy"

# The '0' has a forward slash that cuts diagonally through the middle of
# the circle, connecting the bottom left part to the top right of the
# oval shape.  Whereas the narrow variants have a dashed forward slash
# which does not connect the two sides as it is positioned inside the
# oval shape.
[buildPlans.iosevka-comfy-duo.variants.design]
cv71 = 9    # 0 oval forward slash
cv90 = 2    # @ traditional four-fold style
cv93 = 2    # % with two circles

# The 'm' character has three legs of equal length, insetad of a shorter
# middle leg.  The short middle leg in the narrow variants is necessary
# for legibility, especially at small point sizes (otherwise the
# character's legs visually blend into what appears to be a solid
# block).
[buildPlans.iosevka-comfy-duo.variants.upright]
cv38 = 5    # m earless normal middle leg

[buildPlans.iosevka-comfy-duo.variants.italic]
cv38 = 1    # m straight normal middle leg

[buildPlans.iosevka-comfy-duo.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-comfy-duo.weights.semilight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy-duo.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy-duo.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-comfy-duo.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-comfy-duo.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-comfy-duo.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-comfy-duo.widths.normal]
shape = 525
menu  = 5
css   = "normal"


# More serified, "motion" shapes
# ------------------------------

[buildPlans.iosevka-comfy-motion]
family = "Iosevka Comfy Motion"
spacing = "normal"
serifs = "slab"
export-glyph-names = false

# It seems we can inherit variants, but not weights, slopes, widths,
# metric-override...
[buildPlans.iosevka-comfy-motion.variants]
inherits = "buildPlans.iosevka-comfy"

[buildPlans.iosevka-comfy-motion.variants.design]
cv01 = 3    # A cap top serif
cv02 = 4    # B cap assymetric with top serif
cv03 = 4    # C cap top inward serif
cv05 = 2    # E cap top-left serif
cv06 = 2    # F cap top-left serif
cv07 = 22   # G cap toothed inward top serif
cv08 = 2    # H cap top-left serif
cv11 = 2    # K cap curly serifless
cv12 = 2    # L cap bottom right serif
cv13 = 7    # M cap short middle leg slanted sides top serif
cv14 = 3    # N cap standard shape top serif
cv15 = 3    # P cap closed top serif
cv16 = 4    # Q cap crossing tail
cv17 = 7    # R cap curly top serif
cv18 = 4    # S cap top inward serif
cv20 = 8    # U cap rounded top serif
cv21 = 3    # V cap top serif
cv22 = 7    # W cap top serif
cv23 = 3    # X cap top serif
cv24 = 5    # Y cap top serif
cv25 = 19   # Z cap top serif
cv26 = 2    # a double storey tailed
cv27 = 4    # b toothed top serif
cv28 = 4    # c top inward serif
cv29 = 9    # d tailed top serif
cv32 = 8    # g single storey flat hook serified top
cv33 = 4    # h tailed top serif
cv34 = 8    # i serified tailed
cv36 = 8    # k curly top serif
cv37 = 8    # l serified tailed
cv38 = 20   # m top serif tailed with short middle leg
cv39 = 8    # n top serif tailed
cv40 = 4    # p top serif
cv41 = 4    # q top serif
cv42 = 15   # r top serif hooked
cv43 = 4    # s top inward serif
cv45 = 4    # u tailed
cv46 = 4    # v top serif
cv47 = 8    # w top serif
cv48 = 3    # x top serif
cv49 = 12   # y cursive flat terminal hook serified
cv50 = 19   # z top serif

[buildPlans.iosevka-comfy-motion.variants.upright]
cv31 = 6    # f serifless bottom flat curved crossbar at x height

[buildPlans.iosevka-comfy-motion.variants.italic]
cv31 = 9    # f extended bottom flat curved crossbar at x height
cv44 = 1    # t curly

[buildPlans.iosevka-comfy-motion.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-comfy-motion.weights.semilight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy-motion.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy-motion.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-comfy-motion.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-comfy-motion.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-comfy-motion.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-comfy-motion.widths.normal]
shape = 525
menu  = 5
css   = "normal"


# "Motion" variant with fixed spacing (no ligatures)
# --------------------------------------------------
[buildPlans.iosevka-comfy-motion-fixed]
family = "Iosevka Comfy Motion Fixed"
spacing = "fixed"
serifs = "slab"
export-glyph-names = false

# It seems we can inherit variants, but not weights, slopes, widths,
# metric-override...
[buildPlans.iosevka-comfy-motion-fixed.variants]
inherits = "buildPlans.iosevka-comfy-motion"

[buildPlans.iosevka-comfy-motion-fixed.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-comfy-motion-fixed.weights.semilight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy-motion-fixed.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy-motion-fixed.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-comfy-motion-fixed.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-comfy-motion-fixed.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-comfy-motion-fixed.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-comfy-motion-fixed.widths.normal]
shape = 525
menu  = 5
css   = "normal"


# Iosevka Comfy Motion with Duo spacing (quasi-proportional)
# -----------------------------------------------------------
[buildPlans.iosevka-comfy-motion-duo]
family = "Iosevka Comfy Motion Duo"
spacing = "quasi-proportional"
serifs = "slab"
export-glyph-names = false

# It seems we can inherit variants, but not weights, slopes, widths,
# metric-override...
[buildPlans.iosevka-comfy-motion-duo.variants]
inherits = "buildPlans.iosevka-comfy-motion"

[buildPlans.iosevka-comfy-motion-duo.variants.design]
cv38 = 19   # m top serif tailed with normal middle leg
cv71 = 9    # 0 oval forward slash
cv90 = 2    # @ traditional four-fold style
cv93 = 2    # % with two circles

[buildPlans.iosevka-comfy-motion-duo.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-comfy-motion-duo.weights.semilight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy-motion-duo.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy-motion-duo.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-comfy-motion-duo.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-comfy-motion-duo.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-comfy-motion-duo.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-comfy-motion-duo.widths.normal]
shape = 525
menu  = 5
css   = "normal"


# Like iosevka-comfy but expanded
# -------------------------------
[buildPlans.iosevka-comfy-wide]
family = "Iosevka Comfy Wide"
spacing = "normal"
serifs = "sans"
export-glyph-names = false

# It seems we can inherit variants, but not weights, slopes, widths,
# metric-override...
[buildPlans.iosevka-comfy-wide.variants]
inherits = "buildPlans.iosevka-comfy"

# The '0' has a forward slash that cuts diagonally through the middle of
# the circle, connecting the bottom left part to the top right of the
# oval shape.  Whereas the narrow variants have a dashed forward slash
# which does not connect the two sides as it is positioned inside the
# oval shape.
[buildPlans.iosevka-comfy-wide.variants.design]
cv71 = 9    # 0 oval forward slash
cv90 = 2    # @ traditional four-fold style
cv93 = 2    # % with two circles

# The 'm' character has three legs of equal length, insetad of a shorter
# middle leg.  The short middle leg in the narrow variants is necessary
# for legibility, especially at small point sizes (otherwise the
# character's legs visually blend into what appears to be a solid
# block).
[buildPlans.iosevka-comfy-wide.variants.upright]
cv38 = 5    # m earless normal middle leg

[buildPlans.iosevka-comfy-wide.variants.italic]
cv38 = 1    # m straight normal middle leg

[buildPlans.iosevka-comfy-wide.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-comfy-wide.weights.semilight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy-wide.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy-wide.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-comfy-wide.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-comfy-wide.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-comfy-wide.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-comfy-wide.widths.normal]
shape = 625
menu  = 7
css   = "normal"


# Like iosevka-comfy-wide but fixed monospace (no ligatures)
# ----------------------------------------------------------
[buildPlans.iosevka-comfy-wide-fixed]
family = "Iosevka Comfy Wide Fixed"
spacing = "fixed"
serifs = "sans"
export-glyph-names = false

# It seems we can inherit variants, but not weights, slopes, widths,
# metric-override...
[buildPlans.iosevka-comfy-wide-fixed.variants]
inherits = "buildPlans.iosevka-comfy-wide"

[buildPlans.iosevka-comfy-wide-fixed.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-comfy-wide-fixed.weights.semilight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy-wide-fixed.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy-wide-fixed.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-comfy-wide-fixed.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-comfy-wide-fixed.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-comfy-wide-fixed.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-comfy-wide-fixed.widths.normal]
shape = 625
menu  = 7
css   = "normal"


# Duo spacing but wider (quasi-proportional)
# ------------------------------------------
[buildPlans.iosevka-comfy-wide-duo]
family = "Iosevka Comfy Wide Duo"
spacing = "quasi-proportional"
serifs = "sans"
export-glyph-names = false

# It seems we can inherit variants, but not weights, slopes, widths,
# metric-override...
[buildPlans.iosevka-comfy-wide-duo.variants]
inherits = "buildPlans.iosevka-comfy-wide"

[buildPlans.iosevka-comfy-wide-duo.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-comfy-wide-duo.weights.semilight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy-wide-duo.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy-wide-duo.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-comfy-wide-duo.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-comfy-wide-duo.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-comfy-wide-duo.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-comfy-wide-duo.widths.normal]
shape = 625
menu  = 7
css   = "normal"
